### ISSUE TITLE
Remove dependency to Neos

### ISSUE THREAD

**Issue by grebaldi** [kitsunet/Flowpack.SimpleSearch.ContentRepositoryAdaptor#9]
Hi you guys,

by now I had several occasions where I wanted to use SimpleSearch in use cases where Neos is not involved. 

Since adding SimpleSearch to your dependencies now means that you're getting Neos and the Media Package etc. pp. - which is certainly not needed for this - wouldn't it be possible to just drop the composer dependency?

I had a quick look around this repository and don't see any reason to keep Neos as a dependency. When I'd had a good test case, I would initiate a pull request, but I think you guys have deeper insight to decide this more quickly.

Thanks!

**Comment by kitsunet** [comment]
Hey,
I will check that, makes sense at least :)

**Comment by kitsunet** [comment]
Have changed that.
